### PR TITLE
Allow Babel config based on babelrc files

### PR DESCRIPTION
**Pull request by RafalFilipek**
Hi!

There is only one change in `worker.ts` but I need help with tests. I made some and it works. I'm not sure how to test `dev` mode.

I'll appreciate your feedback :)

Fix for #360.

### CODE REVIEW

**Comment by RafalFilipek** [comment]
@mitchellhamilton I can see from your timeline that you're quite busy, but I wondered if there is anything I can add to this MR?

**Comment by mitchellhamilton** [comment]
I've been thinking about this and I think I'd like to not add `babelrcRoots: true` for a couple reasons and instead recommend that people add `babelrcRoots: true` to their Babel config if they need it since

- Most people don't need it
- It adds more fs calls
- It would make preconstruct dev usage more complicated if it was configured in Preconstruct itself since the require hook and `@preconstruct/next` would need it but more importantly, it would mean another thing people would have to set in other places where they currently just have to set `cwd` or `rootMode: 'upward-optional'`

**Comment by Andarist** [comment]
TIL that `babelrcRoots` can be configured in the `babel.config.js`

**Comment by RafalFilipek** [comment]
True :)

Right now I have `babel.config.js` with `babelrcRoots` and it works super cool with packages and apps. I have 2 NextJS app and 4 packages, each with separated `.babelrc.js`. All possible combinations work just fine.

**Pull request closed without merging**
